const book_order = {
    // This list converts the 10^6 of a rid to a book name.
    "index": [
        // Old Testament
        "Genesis",
        "Exodus",
        "Leviticus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "Ruth",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "1 Chronicles",
        "2 Chronicles",
        "Ezra",
        "Nehemiah",
        "Esther",
        "Job",
        "Psalms",
        "Proverbs",
        "Ecclesiastes",
        "Song of Solomon",
        "Isaiah",
        "Jeremiah",
        "Lamentations",
        "Ezekiel",
        "Daniel",
        "Hosea",
        "Joel",
        "Amos",
        "Obadiah",
        "Jonah",
        "Micah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi",
        // New Testament
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation",
        // Apocryphal
        "1 Esdras",
        "Tobit",
        "Judith",
        "1 Maccabees",
        "2 Maccabees",
        "3 Maccabees",
        "Prayer of Manasseh",
        "Wisdom",
        "Sirach",
        "Psalms of Solomon",
        "Baruch",
        "Letter of Jeremiah",
    ],
    "kjv": [
        // Old Testament
        "Genesis",
        "Exodus",
        "Leviticus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "Ruth",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "1 Chronicles",
        "2 Chronicles",
        "Ezra",
        "Nehemiah",
        "Esther",
        "Job",
        "Psalms",
        "Proverbs",
        "Ecclesiastes",
        "Song of Solomon",
        "Isaiah",
        "Jeremiah",
        "Lamentations",
        "Ezekiel",
        "Daniel",
        "Hosea",
        "Joel",
        "Amos",
        "Obadiah",
        "Jonah",
        "Micah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi",
        // Apocryphal
        "1 Esdras",
        "Tobit",
        "Judith",
        "1 Maccabees",
        "2 Maccabees",
        "3 Maccabees",
        "Prayer of Manasseh",
        "Wisdom",
        "Sirach",
        "Psalms of Solomon",
        "Baruch",
        "Letter of Jeremiah",
        // New Testament
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation",
    ],
    "bhs": [
        // Old Testament
        "Genesis",
        "Exodus",
        "Leviticus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "Isaiah",
        "Jeremiah",
        "Ezekiel",
        "Hosea",
        "Joel",
        "Amos",
        "Obadiah",
        "Jonah",
        "Micah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi",
        "Psalms",
        "Proverbs",
        "Job",
        "Song of Solomon",
        "Ruth",
        "Lamentations",
        "Ecclesiastes",
        "Esther",
        "Daniel",
        "Ezra",
        "Nehemiah",
        "1 Chronicles",
        "2 Chronicles",
        // Apocryphal
        "1 Esdras",
        "Tobit",
        "Judith",
        "1 Maccabees",
        "2 Maccabees",
        "3 Maccabees",
        "Prayer of Manasseh",
        "Wisdom",
        "Sirach",
        "Psalms of Solomon",
        "Baruch",
        "Letter of Jeremiah",
        // New Testament
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation",
    ],
    "lxx": [
        // Old Testament and Apocrypha
        "Genesis",
        "Exodus",
        "Leviticus",
        "Numbers",
        "Deuteronomy",
        "Joshua",
        "Judges",
        "Ruth",
        "1 Samuel",
        "2 Samuel",
        "1 Kings",
        "2 Kings",
        "1 Chronicles",
        "2 Chronicles",
        "1 Esdras",
        "Ezra",
        "Nehemiah",
        "Tobit",
        "Judith",
        "Esther",
        "1 Maccabees",
        "2 Maccabees",
        "3 Maccabees",
        "Psalms",
        "Prayer of Manasseh",
        "Job",
        "Proverbs",
        "Ecclesiastes",
        "Song of Solomon",
        "Wisdom",
        "Sirach",
        "Psalms of Solomon",
        "Hosea",
        "Amos",
        "Micah",
        "Joel",
        "Obadiah",
        "Jonah",
        "Nahum",
        "Habakkuk",
        "Zephaniah",
        "Haggai",
        "Zechariah",
        "Malachi",
        "Isaiah",
        "Jeremiah",
        "Baruch",
        "Lamentations",
        "Letter of Jeremiah",
        "Ezekiel",
        "Daniel",
        // New Testament
        "Matthew",
        "Mark",
        "Luke",
        "John",
        "Acts",
        "Romans",
        "1 Corinthians",
        "2 Corinthians",
        "Galatians",
        "Ephesians",
        "Philippians",
        "Colossians",
        "1 Thessalonians",
        "2 Thessalonians",
        "1 Timothy",
        "2 Timothy",
        "Titus",
        "Philemon",
        "Hebrews",
        "James",
        "1 Peter",
        "2 Peter",
        "1 John",
        "2 John",
        "3 John",
        "Jude",
        "Revelation",
    ]
}
book_order["gnt"] = book_order["kjv"].slice(0)

const setDifference = (a, b) => {
    const s1 = Array.from(a).filter(x => !b.has(x))
    const s2 = Array.from(b).filter(x => !a.has(x))
    return s1.concat(s2)
}

// Sanity check (every book needs to be represented in every key)
const indexBookSet = new Set(book_order["index"])
for (let key in book_order) {
    if (key === "index") {
        continue
    }
    console.log(key)
    const booksByKey = new Set(book_order[key])

    const bookDifference = setDifference(booksByKey, indexBookSet)
    if (bookDifference.length > 0) {
        console.error("Missing books in " + key + ": " + bookDifference)
        throw ("Every book order must contain every book and only those elements")
    }
}

module.exports = book_order