module.exports = [
    { "name": "Genesis", "chapters": 50, "abbreviation": "Gen" },
    { "name": "Exodus", "chapters": 40, "abbreviation": "Exod" },
    { "name": "Leviticus", "chapters": 27, "abbreviation": "Lev" },
    { "name": "Numbers", "chapters": 36, "abbreviation": "Num" },
    { "name": "Deuteronomy", "chapters": 34, "abbreviation": "Deut" },
    { "name": "Joshua", "chapters": 24, "abbreviation": "Josh" },
    { "name": "Judges", "chapters": 21, "abbreviation": "Judg" },
    { "name": "Ruth", "chapters": 4, "abbreviation": "Ruth" },
    { "name": "1 Samuel", "chapters": 31, "abbreviation": "1 Sam" },
    { "name": "2 Samuel", "chapters": 24, "abbreviation": "2 Sam" },
    { "name": "1 Kings", "chapters": 22, "abbreviation": "1 Kgs" },
    { "name": "2 Kings", "chapters": 25, "abbreviation": "2 Kgs" },
    { "name": "1 Chronicles", "chapters": 29, "abbreviation": "1 Chr" },
    { "name": "2 Chronicles", "chapters": 36, "abbreviation": "2 Chr" },
    { "name": "Ezra", "chapters": 10, "abbreviation": "Ezra" },
    { "name": "Nehemiah", "chapters": 13, "abbreviation": "Neh" },
    { "name": "Esther", "chapters": 10, "abbreviation": "Est" },
    { "name": "Job", "chapters": 42, "abbreviation": "Job" },
    { "name": "Psalms", "chapters": 150, "abbreviation": "Ps" },
    { "name": "Proverbs", "chapters": 31, "abbreviation": "Prov" },
    { "name": "Ecclesiastes", "chapters": 12, "abbreviation": "Eccl" },
    { "name": "Song of Songs", "chapters": 8, "abbreviation": "Songs" },
    { "name": "Isaiah", "chapters": 66, "abbreviation": "Isa" },
    { "name": "Jeremiah", "chapters": 52, "abbreviation": "Jer" },
    { "name": "Lamentations", "chapters": 5, "abbreviation": "Lam" },
    { "name": "Ezekiel", "chapters": 48, "abbreviation": "Ezek" },
    { "name": "Daniel", "chapters": 12, "abbreviation": "Dan" },
    { "name": "Hosea", "chapters": 14, "abbreviation": "Hos" },
    { "name": "Joel", "chapters": 4, "abbreviation": "Joel" },
    { "name": "Amos", "chapters": 9, "abbreviation": "Amos" },
    { "name": "Obadiah", "chapters": 1, "abbreviation": "Obad" },
    { "name": "Jonah", "chapters": 4, "abbreviation": "Jonah" },
    { "name": "Micah", "chapters": 7, "abbreviation": "Mic" },
    { "name": "Nahum", "chapters": 3, "abbreviation": "Nah" },
    { "name": "Habakkuk", "chapters": 3, "abbreviation": "Hab" },
    { "name": "Zephaniah", "chapters": 3, "abbreviation": "Zeph" },
    { "name": "Haggai", "chapters": 2, "abbreviation": "Hag" },
    { "name": "Zechariah", "chapters": 14, "abbreviation": "Zech" },
    { "name": "Malachi", "chapters": 3, "abbreviation": "Mal" },

    { "name": "Matthew", "chapters": 28, "abbreviation": "Matt" },
    { "name": "Mark", "chapters": 16, "abbreviation": "Mark" },
    { "name": "Luke", "chapters": 24, "abbreviation": "Luke" },
    { "name": "John", "chapters": 21, "abbreviation": "John" },
    { "name": "Acts", "chapters": 28, "abbreviation": "Acts" },
    { "name": "Romans", "chapters": 16, "abbreviation": "Rom" },
    { "name": "1 Corinthians", "chapters": 16, "abbreviation": "1 Cor" },
    { "name": "2 Corinthians", "chapters": 13, "abbreviation": "2 Cor" },
    { "name": "Galatians", "chapters": 6, "abbreviation": "Gal" },
    { "name": "Ephesians", "chapters": 6, "abbreviation": "Eph" },
    { "name": "Philippians", "chapters": 4, "abbreviation": "Phil" },
    { "name": "Colossians", "chapters": 4, "abbreviation": "Col" },
    { "name": "1 Thessalonians", "chapters": 5, "abbreviation": "1 Thess" },
    { "name": "2 Thessalonians", "chapters": 3, "abbreviation": "2 Thess" },
    { "name": "1 Timothy", "chapters": 6, "abbreviation": "1 Tim" },
    { "name": "2 Timothy", "chapters": 4, "abbreviation": "2 Tim" },
    { "name": "Titus", "chapters": 3, "abbreviation": "Titus" },
    { "name": "Philemon", "chapters": 1, "abbreviation": "Phlm" },
    { "name": "Hebrews", "chapters": 13, "abbreviation": "Heb" },
    { "name": "James", "chapters": 5, "abbreviation": "Jas" },
    { "name": "1 Peter", "chapters": 5, "abbreviation": "1 Pet" },
    { "name": "2 Peter", "chapters": 3, "abbreviation": "2 Pet" },
    { "name": "1 John", "chapters": 5, "abbreviation": "1 John" },
    { "name": "2 John", "chapters": 1, "abbreviation": "2 John" },
    { "name": "3 John", "chapters": 1, "abbreviation": "3 John" },
    { "name": "Jude", "chapters": 1, "abbreviation": "Jude" },
    { "name": "Revelation", "chapters": 22, "abbreviation": "Rev" }
]
