// I'm just saving this because of the frequency with which I find myself creating this kind of list
// This also includes the apocrypha and apostolic fathers (in an order)

// COMPLETE LIST OF BOOKS AVAILABLE (by normalized name)
const BOOKS = [
    // Make the first book "1"
    "EMPTY",

    // Old Testament
    "Genesis",
    "Exodus",
    "Leviticus",
    "Numbers",
    "Deuteronomy",
    "Joshua",
    "Judges",
    "Ruth",
    "1 Samuel",
    "2 Samuel",
    "1 Kings",
    "2 Kings",
    "1 Chronicles",
    "2 Chronicles",
    "Ezra",
    "Nehemiah",
    "Esther",
    "Job",
    "Psalms",
    "Proverbs",
    "Ecclesiastes",
    "Song of Songs",
    "Isaiah",
    "Jeremiah",
    "Lamentations",
    "Ezekiel",
    "Daniel",
    "Hosea",
    "Joel",
    "Amos",
    "Obadiah",
    "Jonah",
    "Micah",
    "Nahum",
    "Habakkuk",
    "Zephaniah",
    "Haggai",
    "Zechariah",
    "Malachi",

    // New Testament
    "Matthew",
    "Mark",
    "Luke",
    "John",
    "Acts",
    "Romans",
    "1 Corinthians",
    "2 Corinthians",
    "Galatians",
    "Ephesians",
    "Philippians",
    "Colossians",
    "1 Thessalonians",
    "2 Thessalonians",
    "1 Timothy",
    "2 Timothy",
    "Titus",
    "Philemon",
    "Hebrews",
    "James",
    "1 Peter",
    "2 Peter",
    "1 John",
    "2 John",
    "3 John",
    "Jude",
    "Revelation",

    // Apocrypha
    "Tobit",
    "Judith",
    "Baruch",
    "Wisdom of Solomon",
    "Sirach",
    "Baruch",
    "Epistle of Jeremiah",
    "Susanna",
    "Bel and the Dragon",
    "1 Maccabees",
    "2 Maccabees",
    "1 Esdras",
    "Psalms of Manasseh",
    "3 Maccabees",
    "2 Esdras",
    "4 Maccabees",

    // Apostolic Fathers
    "Barnabas",
    "1 Clement",
    "2 Clement",
    "Didache",
    "Diognetus",
    "Shepherd of Hermas",
    "Ignatius, To the Ephesians",
    "Ignatius, To the Magnesians",
    "Ignatius, To the Philadelphians",
    "Ignatius, To Polycarp",
    "Ignatius, To the Romans",
    "Ignatius, To the Smyrnaeans",
    "Ignatius, To the Trallians",
    "Martyrdom of Polycarp",
    "Polycarp, To the Philippians",
]